baseURL = "/"
languageCode = "de-ch"
title = "Air Festival 21"
assetDir = "assets"
relativeURLs = true
googleAnalytics = "UA-25486694-1"
[taxonomies]
    category = "categories"

[params]
    coverImage = "/img/cover/flugschule.jpg"

[menu]
    [[menu.main]]
    identifier = "flugplatz"
    name       = "Flugplatz"
    url        = "/flugplatz/"
    weight     = 1

    [[menu.main]]
    identifier = "kontakt"
    name       = "Kontakt"
    url        = "/kontakt/"
    weight     = 6

[sitemap]
  changefreq  = "monthly"
  filename    = "sitemap.xml"
  priority    = 0.5

[blackfriday]
  hrefTargetBlank = true
