backend:
  name: git-gateway
  branch: master
  # publish_mode: editorial_workflow
media_folder: "static/img/uploads"
public_folder: "/img/uploads"
collections:
  - name: "index"
    label: "Home"
    folder: "content"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - label: "Headerbild/Headerbilder"
        name: "coverImages"
        widget: "list"
        required: true
        fields:
          - {label: "Bild", name: "image", widget: "image", required: true}
          - {label: "Fokuspunkt Horizontal von links in %", name: "positionx", widget: "number", default: 50, valueType: "int", min: 0, max: 100, required: true}
          - {label: "Fokuspunkt Vertikal von oben in %", name: "positiony", widget: "number", default: 50, valueType: "int", min: 0, max: 100, required: true}
  - name: "index-news"
    label: "Home - News"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Veröffentlichungsdatum", name: "date", widget: "datetime", required: false}
      - {label: "Entwurf", name: "draft", widget: "boolean", default: true, required: false}
      - {label: "Bild", name: "image", widget: "image", required: true}
      - {label: "Fokuspunkt Horizontal von links in %", name: "positionx", widget: "number", default: 50, valueType: "int", min: 0, max: 100, required: true}
      - {label: "Fokuspunkt Vertikal von oben in %", name: "positiony", widget: "number", default: 50, valueType: "int", min: 0, max: 100, required: true}
      - {label: "Teaser", name: "description", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - label: "Buttons"
        name: "buttons"
        widget: "list"
        required: false
        fields:
          - {label: "Titel", name: "title", widget: "string", required: false}
          - {label: "URL", name: "url", widget: "string"}
          - {label: "CTA", name: "cta", widget: "boolean", required: false}
          - {label: "In neuem Tab öffnen", name: "blank", widget: "boolean", default: true, required: false}
      - label: "Headerbild/Headerbilder"
        name: "coverImages"
        widget: "list"
        required: false
        fields:
          - {label: "Bild", name: "image", widget: "image", required: true}
          - {label: "Fokuspunkt Horizontal von links in %", name: "positionx", widget: "number", default: 50, valueType: "int", min: 0, max: 100, required: true}
          - {label: "Fokuspunkt Vertikal von oben in %", name: "positiony", widget: "number", default: 50, valueType: "int", min: 0, max: 100, required: true}
  - name: "flugplatz"
    label: "Flugplatz"
    folder: "content/flugplatz/"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Veröffentlichungsdatum", name: "date", widget: "datetime", required: false}
      - {label: "Entwurf", name: "draft", widget: "boolean", default: true, required: false}
      - {label: "Gewichtung", name: "weight", widget: "number", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - label: "Headerbild/Headerbilder"
        name: "coverImages"
        widget: "list"
        required: true
        fields:
          - {label: "Bild", name: "image", widget: "image", required: true}
          - {label: "Fokuspunkt Horizontal von links in %", name: "positionx", widget: "number", default: 50, valueType: "int", min: 0, max: 100, required: true}
          - {label: "Fokuspunkt Vertikal von oben in %", name: "positiony", widget: "number", default: 50, valueType: "int", min: 0, max: 100, required: true}
  - name: "kontakt"
    label: "Kontakt"
    folder: "content/kontakt/"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Veröffentlichungsdatum", name: "date", widget: "datetime", required: false}
      - {label: "Entwurf", name: "draft", widget: "boolean", default: true, required: false}
      - {label: "Gewichtung", name: "weight", widget: "number", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - label: "Headerbild/Headerbilder"
        name: "coverImages"
        widget: "list"
        required: true
        fields:
          - {label: "Bild", name: "image", widget: "image", required: true}
          - {label: "Fokuspunkt Horizontal von links in %", name: "positionx", widget: "number", default: 50, valueType: "int", min: 0, max: 100, required: true}
          - {label: "Fokuspunkt Vertikal von oben in %", name: "positiony", widget: "number", default: 50, valueType: "int", min: 0, max: 100, required: true}
