backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  # publish_mode: editorial_workflow
media_folder: "static/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News" # Used in the UI
    folder: "content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Veröffentlichungsdatum", name: "date", widget: "datetime", required: false }
      - {label: "Entwurf", name: "draft", widget: "boolean", default: true, require: false }
      - {label: "Gewichtung", name: "weight", widget: "string", required: false}
      - {label: "Bild", name: "image", widget: "image", required: false}
      - {label: "Teaser", name: "description", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "flugplatz" # Used in routes, e.g., /admin/collections/blog
    label: "Flugplatz" # Used in the UI
    folder: "content/flugplatz/{{slug}}" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Veröffentlichungsdatum", name: "date", widget: "datetime", required: false }
      - {label: "Entwurf", name: "draft", widget: "boolean", default: true, require: false }
      - {label: "Gewichtung", name: "weight", widget: "string", required: false}
      - {label: "Bild", name: "image", widget: "image", required: false}
      - {label: "Teaser", name: "description", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}