backend:
  name: git-gateway
  branch: master
  # publish_mode: editorial_workflow
media_folder: "static/img/uploads"
public_folder: "/img/uploads"
collections:
  - name: "index"
    label: "Home"
    folder: "content"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Bild", name: "coverImageUrl", widget: "image", required: true}
  - name: "index-news"
    label: "Home - News"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Veröffentlichungsdatum", name: "date", widget: "datetime", required: false }
      - {label: "Entwurf", name: "draft", widget: "boolean", default: true, require: false }
      - {label: "Bild", name: "image", widget: "image", required: false}
      - {label: "Teaser", name: "description", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Buttons"
        name: "buttons"
        widget: "list"
        fields:
          - {label: "Titel", name: "title", widget: "string", required: false}
          - {label: "URL", name: "url", widget: "string"}
          - {label: "CTA", name: "cta", widget: "boolean", required: false}
  - name: "flugplatz"
    label: "Flugplatz"
    folder: "content/flugplatz/"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Veröffentlichungsdatum", name: "date", widget: "datetime", required: false }
      - {label: "Entwurf", name: "draft", widget: "boolean", default: true, require: false }
      - {label: "Gewichtung", name: "weight", widget: "number", required: false}
      - {label: "Bild", name: "image", widget: "image", required: false}
      - {label: "Teaser", name: "description", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Buttons"
        name: "buttons"
        widget: "list"
        fields:
          - {label: "Titel", name: "title", widget: "string", required: false}
          - {label: "URL", name: "url", widget: "string"}
          - {label: "CTA", name: "cta", widget: "boolean", required: false}
  - name: "flugplatz-infos-piloten"
    label: "Flugplatz - Infos für Piloten"
    folder: "content/flugplatz/infos-piloten"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Veröffentlichungsdatum", name: "date", widget: "datetime", required: false }
      - {label: "Entwurf", name: "draft", widget: "boolean", default: true, require: false }
      - {label: "Gewichtung", name: "weight", widget: "number", required: false}
      - {label: "Bild", name: "image", widget: "image", required: false}
      - {label: "Teaser", name: "description", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Buttons"
        name: "buttons"
        widget: "list"
        fields:
          - {label: "Titel", name: "title", widget: "string", required: false}
          - {label: "URL", name: "url", widget: "string"}
          - {label: "CTA", name: "cta", widget: "boolean", required: false}
  - name: "flugplatz-gastronomie"
    label: "Flugplatz - Gastronomie"
    folder: "content/flugplatz/gastronomie"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Veröffentlichungsdatum", name: "date", widget: "datetime", required: false }
      - {label: "Entwurf", name: "draft", widget: "boolean", default: true, require: false }
      - {label: "Gewichtung", name: "weight", widget: "number", required: false}
      - {label: "Bild", name: "image", widget: "image", required: false}
      - {label: "Teaser", name: "description", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Buttons"
        name: "buttons"
        widget: "list"
        fields:
          - {label: "Titel", name: "title", widget: "string", required: false}
          - {label: "URL", name: "url", widget: "string"}
          - {label: "CTA", name: "cta", widget: "boolean", required: false}
